import type { Recipe } from "./types";

export const recipes: Recipe[] = [
  {
    id: "bf-oatmeal",
    name: "Berry Oatmeal Bowl",
    meal: "breakfast",
    diet: ["vegetarian", "vegan", "gluten-free"],
    containsMeat: false,
    effort: "quick",
    costPerServing: 1.5,
    prepMins: 10,
    ingredients: [
      { item: "rolled oats", qty: 0.5, unit: "cup", cost: 0.4, category: "grain" },
      { item: "almond milk", qty: 1, unit: "cup", cost: 0.6, category: "other" },
      { item: "mixed berries", qty: 0.5, unit: "cup", cost: 0.5, category: "produce" },
    ],
  },
  {
    id: "bf-eggs",
    name: "Scrambled Eggs & Toast",
    meal: "breakfast",
    diet: ["vegetarian"],
    containsMeat: false,
    effort: "quick",
    costPerServing: 2.0,
    prepMins: 12,
    ingredients: [
      { item: "eggs", qty: 2, unit: "large", cost: 0.8, category: "other" },
      { item: "butter", qty: 1, unit: "tbsp", cost: 0.3, category: "dairy" },
      { item: "bread", qty: 2, unit: "slices", cost: 0.9, category: "grain" },
    ],
  },
  {
    id: "bf-pancakes",
    name: "Fluffy Pancakes",
    meal: "breakfast",
    diet: ["vegetarian"],
    containsMeat: false,
    effort: "medium",
    costPerServing: 2.5,
    prepMins: 25,
    ingredients: [
      { item: "flour", qty: 1, unit: "cup", cost: 0.4, category: "grain" },
      { item: "milk", qty: 0.75, unit: "cup", cost: 0.5, category: "dairy" },
      { item: "eggs", qty: 1, unit: "large", cost: 0.4, category: "other" },
      { item: "maple syrup", qty: 2, unit: "tbsp", cost: 1.2, category: "other" },
    ],
  },
  {
    id: "bf-smoothie",
    name: "Green Power Smoothie",
    meal: "breakfast",
    diet: ["vegetarian", "vegan", "gluten-free"],
    containsMeat: false,
    effort: "quick",
    costPerServing: 3.0,
    prepMins: 5,
    ingredients: [
      { item: "spinach", qty: 1, unit: "cup", cost: 0.6, category: "produce" },
      { item: "banana", qty: 1, unit: "medium", cost: 0.4, category: "produce" },
      { item: "greek yogurt", qty: 0.5, unit: "cup", cost: 1.2, category: "dairy" },
      { item: "honey", qty: 1, unit: "tbsp", cost: 0.8, category: "other" },
    ],
  },
  {
    id: "ln-salad",
    name: "Garden Salad with Chickpeas",
    meal: "lunch",
    diet: ["vegetarian", "vegan", "gluten-free"],
    containsMeat: false,
    effort: "quick",
    costPerServing: 3.5,
    prepMins: 15,
    ingredients: [
      { item: "mixed greens", qty: 2, unit: "cups", cost: 1.0, category: "produce" },
      { item: "chickpeas", qty: 0.5, unit: "cup", cost: 0.8, category: "other" },
      { item: "olive oil", qty: 1, unit: "tbsp", cost: 0.4, category: "other" },
      { item: "lemon", qty: 0.5, unit: "medium", cost: 0.3, category: "produce" },
    ],
  },
  {
    id: "ln-sandwich",
    name: "Turkey Club Sandwich",
    meal: "lunch",
    diet: [],
    containsMeat: true,
    effort: "quick",
    costPerServing: 4.5,
    prepMins: 10,
    ingredients: [
      { item: "turkey slices", qty: 4, unit: "oz", cost: 2.5, category: "meat" },
      { item: "bread", qty: 3, unit: "slices", cost: 1.0, category: "grain" },
      { item: "lettuce", qty: 2, unit: "leaves", cost: 0.3, category: "produce" },
      { item: "mayonnaise", qty: 1, unit: "tbsp", cost: 0.7, category: "other" },
    ],
  },
  {
    id: "ln-pasta",
    name: "Creamy Mushroom Pasta",
    meal: "lunch",
    diet: ["vegetarian"],
    containsMeat: false,
    effort: "medium",
    costPerServing: 4.0,
    prepMins: 30,
    ingredients: [
      { item: "pasta", qty: 2, unit: "oz", cost: 0.6, category: "grain" },
      { item: "mushrooms", qty: 1, unit: "cup", cost: 1.2, category: "produce" },
      { item: "heavy cream", qty: 0.25, unit: "cup", cost: 1.5, category: "dairy" },
      { item: "parmesan", qty: 2, unit: "tbsp", cost: 0.7, category: "dairy" },
    ],
  },
  {
    id: "ln-bowl",
    name: "Buddha Bowl",
    meal: "lunch",
    diet: ["vegetarian", "vegan", "gluten-free"],
    containsMeat: false,
    effort: "medium",
    costPerServing: 5.0,
    prepMins: 35,
    ingredients: [
      { item: "quinoa", qty: 0.5, unit: "cup", cost: 1.0, category: "grain" },
      { item: "tofu", qty: 4, unit: "oz", cost: 1.5, category: "other" },
      { item: "broccoli", qty: 1, unit: "cup", cost: 0.8, category: "produce" },
      { item: "tahini", qty: 1, unit: "tbsp", cost: 1.7, category: "other" },
    ],
  },
  {
    id: "dn-stirfry",
    name: "Vegetable Stir Fry",
    meal: "dinner",
    diet: ["vegetarian", "vegan", "gluten-free"],
    containsMeat: false,
    effort: "quick",
    costPerServing: 4.5,
    prepMins: 20,
    ingredients: [
      { item: "rice", qty: 0.75, unit: "cup", cost: 0.5, category: "grain" },
      { item: "bell pepper", qty: 1, unit: "medium", cost: 0.8, category: "produce" },
      { item: "soy sauce", qty: 2, unit: "tbsp", cost: 0.3, category: "other" },
      { item: "tofu", qty: 4, unit: "oz", cost: 1.5, category: "other" },
    ],
  },
  {
    id: "dn-steak",
    name: "Pan-Seared Steak",
    meal: "dinner",
    diet: [],
    containsMeat: true,
    effort: "medium",
    costPerServing: 9.0,
    prepMins: 25,
    ingredients: [
      { item: "sirloin steak", qty: 8, unit: "oz", cost: 6.5, category: "meat" },
      { item: "butter", qty: 1, unit: "tbsp", cost: 0.3, category: "dairy" },
      { item: "potatoes", qty: 1, unit: "medium", cost: 0.5, category: "produce" },
      { item: "garlic", qty: 2, unit: "cloves", cost: 0.2, category: "produce" },
    ],
  },
  {
    id: "dn-salmon",
    name: "Baked Salmon with Asparagus",
    meal: "dinner",
    diet: ["gluten-free"],
    containsMeat: true,
    effort: "medium",
    costPerServing: 8.5,
    prepMins: 30,
    ingredients: [
      { item: "salmon fillet", qty: 6, unit: "oz", cost: 5.5, category: "meat" },
      { item: "asparagus", qty: 8, unit: "spears", cost: 1.5, category: "produce" },
      { item: "olive oil", qty: 1, unit: "tbsp", cost: 0.4, category: "other" },
      { item: "lemon", qty: 0.5, unit: "medium", cost: 0.3, category: "produce" },
    ],
  },
  {
    id: "dn-curry",
    name: "Chickpea Coconut Curry",
    meal: "dinner",
    diet: ["vegetarian", "vegan", "gluten-free"],
    containsMeat: false,
    effort: "elaborate",
    costPerServing: 5.5,
    prepMins: 45,
    ingredients: [
      { item: "chickpeas", qty: 1, unit: "cup", cost: 1.0, category: "other" },
      { item: "coconut milk", qty: 0.5, unit: "cup", cost: 1.2, category: "other" },
      { item: "curry powder", qty: 1, unit: "tbsp", cost: 0.5, category: "other" },
      { item: "rice", qty: 0.75, unit: "cup", cost: 0.5, category: "grain" },
      { item: "onion", qty: 0.5, unit: "medium", cost: 0.4, category: "produce" },
    ],
  },
  {
    id: "dn-tacos",
    name: "Beef Tacos",
    meal: "dinner",
    diet: [],
    containsMeat: true,
    effort: "quick",
    costPerServing: 6.0,
    prepMins: 20,
    ingredients: [
      { item: "ground beef", qty: 6, unit: "oz", cost: 3.5, category: "meat" },
      { item: "tortillas", qty: 3, unit: "small", cost: 0.8, category: "grain" },
      { item: "cheddar cheese", qty: 0.25, unit: "cup", cost: 0.9, category: "dairy" },
      { item: "salsa", qty: 0.25, unit: "cup", cost: 0.5, category: "other" },
    ],
  },
];

export function getRecipeById(id: string): Recipe | undefined {
  return recipes.find((recipe) => recipe.id === id);
}
